// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjekip_ofpUu9J0agR9nrz8ZaktVKAAVc',
    appId: '1:277267372025:web:70a71048b7347f72f00f28',
    messagingSenderId: '277267372025',
    projectId: 'gestion-sanitaria',
    authDomain: 'gestion-sanitaria.firebaseapp.com',
    storageBucket: 'gestion-sanitaria.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdTLzZAXFT1CdHIOUHdShmpGUABjNVNs',
    appId: '1:277267372025:android:4f5c5f4ed572f821f00f28',
    messagingSenderId: '277267372025',
    projectId: 'gestion-sanitaria',
    storageBucket: 'gestion-sanitaria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3BIAsYCcnhWlL7pvn6lXVyp94qFDYhNU',
    appId: '1:277267372025:ios:8f460ea47bf19b4af00f28',
    messagingSenderId: '277267372025',
    projectId: 'gestion-sanitaria',
    storageBucket: 'gestion-sanitaria.appspot.com',
    iosBundleId: 'com.danielgil.gestionSanitaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3BIAsYCcnhWlL7pvn6lXVyp94qFDYhNU',
    appId: '1:277267372025:ios:8f460ea47bf19b4af00f28',
    messagingSenderId: '277267372025',
    projectId: 'gestion-sanitaria',
    storageBucket: 'gestion-sanitaria.appspot.com',
    iosBundleId: 'com.danielgil.gestionSanitaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjekip_ofpUu9J0agR9nrz8ZaktVKAAVc',
    appId: '1:277267372025:web:0d27c965f5257210f00f28',
    messagingSenderId: '277267372025',
    projectId: 'gestion-sanitaria',
    authDomain: 'gestion-sanitaria.firebaseapp.com',
    storageBucket: 'gestion-sanitaria.appspot.com',
  );
}
